"""Parse the headers OrcaSlicer writes into a .gcode file.

Orca writes a HEADER_BLOCK at the top and a CONFIG_BLOCK at the bottom. The
fields the bridge needs are all `; key = value` comment lines; for a
multi-filament job the value is a `;` separated list, one entry per extruder.

Verified against the head and tail of a real Orca 2.4.2 job taken off the
printer while working this out.
"""
from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from typing import Optional

# `; filament_type = PLA;PETG`
_SETTING = re.compile(r"^;\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$")
# A tool change is a line that is exactly `T<digits>`, optionally commented.
_TOOL = re.compile(r"^T(\d+)\s*(?:;.*)?$")

# Only these keys are collected, so a 20 MB file costs one cheap regex per line.
WANTED = {
    "filament_settings_id",
    "filament_type",
    "filament_colour",
    "filament_ids",
    "filament_vendor",
    "filament_diameter",
    "filament_density",
    "printer_model",
    "printer_settings_id",
    "nozzle_diameter",
    "flush_volumes_matrix",
    "flush_volumes_vector",
}


def _split_list(value: str) -> list[str]:
    """Orca writes per-extruder lists as `a;b;c`, sometimes quoted."""
    value = value.strip()
    if value.startswith('"') and value.endswith('"') and value.count('"') == 2:
        value = value[1:-1]
    parts = [p.strip().strip('"') for p in value.split(";")]
    return [p for p in parts if p != ""] or ([""] if value == "" else [])


@dataclass
class Extruder:
    """One slicer extruder, that is one `T<n>` in the file."""

    index: int                       # 0 based, matches the T number
    filament_type: str = ""
    colour: Optional[str] = None     # "#RRGGBB"
    settings_id: str = ""
    filament_id: str = ""            # Creality material id, e.g. "00001"
    vendor: str = ""

    @property
    def tool(self) -> str:
        return "T%d" % self.index


@dataclass
class GcodeInfo:
    path: str = ""
    name: str = ""
    size: int = 0
    settings: dict = field(default_factory=dict)
    extruders: list[Extruder] = field(default_factory=list)
    tools_used: list[int] = field(default_factory=list)
    generated_by: str = ""

    @property
    def is_multi_filament(self) -> bool:
        return len(self.tools_used) > 1 or len(self.extruders) > 1

    @property
    def looks_like_orca(self) -> bool:
        return "orca" in self.generated_by.lower()


def parse_gcode(path: str, max_tool_scan_bytes: int = 0) -> GcodeInfo:
    """Read an Orca G-code file and pull out the filament headers and tools.

    `max_tool_scan_bytes` of 0 scans the whole file for tool changes, which is
    what a correct tool list needs. The scan is a single pass.
    """
    info = GcodeInfo(path=path, name=os.path.basename(path))
    try:
        info.size = os.path.getsize(path)
    except OSError:
        pass

    seen_tools: list[int] = []
    scanned = 0
    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            scanned += len(line)
            stripped = line.strip()
            if not stripped:
                continue
            if stripped[0] == ";":
                if "generated by" in stripped and not info.generated_by:
                    info.generated_by = stripped.lstrip("; ").strip()
                    continue
                match = _SETTING.match(stripped)
                if match and match.group(1) in WANTED:
                    info.settings[match.group(1)] = match.group(2)
                continue
            if stripped[0] == "T":
                match = _TOOL.match(stripped)
                if match:
                    index = int(match.group(1))
                    if index not in seen_tools:
                        seen_tools.append(index)
            if max_tool_scan_bytes and scanned > max_tool_scan_bytes:
                break

    info.tools_used = sorted(seen_tools)

    types = _split_list(info.settings.get("filament_type", ""))
    colours = _split_list(info.settings.get("filament_colour", ""))
    ids = _split_list(info.settings.get("filament_settings_id", ""))
    fids = _split_list(info.settings.get("filament_ids", ""))
    vendors = _split_list(info.settings.get("filament_vendor", ""))

    count = max(
        len(types), len(colours), len(ids),
        (max(info.tools_used) + 1) if info.tools_used else 0,
        1,
    )
    for i in range(count):
        info.extruders.append(
            Extruder(
                index=i,
                filament_type=types[i] if i < len(types) else "",
                colour=colours[i] if i < len(colours) else None,
                settings_id=ids[i] if i < len(ids) else "",
                filament_id=fids[i] if i < len(fids) else "",
                vendor=vendors[i] if i < len(vendors) else "",
            )
        )

    # A single filament job need not contain any T command at all; the printer
    # still resolves it as tool 0.
    if not info.tools_used:
        info.tools_used = [0]

    return info


def rewrite_tool_numbers(source: str, destination: str, mapping: dict[int, int]) -> int:
    """Rewrite bare `T<n>` lines using `mapping` (old index -> new index).

    Used by `send --method gcode`. Returns the number of lines changed.
    Only lines that are exactly a tool change are touched; `T` inside a comment
    or a parameter is left alone.
    """
    changed = 0
    with open(source, "r", encoding="utf-8", errors="replace") as src, \
            open(destination, "w", encoding="utf-8", newline="") as dst:
        for line in src:
            stripped = line.strip()
            if stripped and stripped[0] == "T":
                match = _TOOL.match(stripped)
                if match:
                    old = int(match.group(1))
                    if old in mapping and mapping[old] != old:
                        dst.write("T%d ; cfsbridge: was T%d\n" % (mapping[old], old))
                        changed += 1
                        continue
            dst.write(line)
    return changed
